### ISSUE TITLE
React components & examples

### ISSUE THREAD

**Issue by hiendv** [hiendv/tabs#1]

**Comment by villa7** [comment]
I can work on this

**Comment by hiendv** [comment]
@villa7 Thank you. You can ping me if you have any question or need pointer to start working. You can take a look at **vue-tabs**.

**Comment by villa7** [comment]
@hiendv Why is webpack unable to resolve the symlinked packages? Lerna created a symlink to `packages/vue-tabs` in `packages/vue-tabs-example/node_modules/@hiendv/vue-tabs`, but I am still getting this error when running `npm run serve:vue`.
![image](https://user-images.githubusercontent.com/1696813/65741178-443e0e80-e0b9-11e9-9576-4890cd32fd2a.png)
The same happens for all other `import`ed local packages.

**Comment by hiendv** [comment]
Did you `npm run setup` after installation?

**Comment by villa7** [comment]
Yes

**Comment by hiendv** [comment]
@villa7 Oh snap, please `npm run build` for vue-tabs dist :rofl: =D My bad, I didn't make it clear enough in the contributing guide.

**Comment by hiendv** [comment]
You can start `npm run watch` or `yarn watch` before running `npm run serve:vue` or `yarn serve:vue` ;)

**Comment by hiendv** [comment]
@villa7 Thank you for taking this. Please [squash your commits into a single one](https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit) so we can review the PR faster.

I take at look at [your work](https://github.com/villa7/tabs/tree/react), it seems like the commitlint isn't working for you. If possible, please follow [the conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/): https://www.npmjs.com/package/@commitlint/config-conventional
Thank you :gift_heart:
